default_language_version:
    python: python3
repos:
    - repo: https://github.com/PyCQA/bandit
      rev: 1.6.2
      hooks:
          - id: bandit
            args: [-lll, --quiet, --exclude=tests/**]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: check-yaml
          - id: debug-statements
          - id: requirements-txt-fixer
          - id: fix-encoding-pragma
            args: [--remove]
          - id: trailing-whitespace
            exclude: ^tests/_testing_data/
    - repo: https://github.com/asottile/seed-isort-config
      rev: v1.9.2
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
            args: [--quiet]
    - repo: https://github.com/asottile/pyupgrade
      rev: v1.23.0
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.4.1
      hooks:
          - id: python-no-eval
          - id: rst-backticks
    - repo: https://github.com/python/black
      rev: 19.3b0
      hooks:
          - id: black
            args: [--safe, --quiet, --target-version=py36]
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.3.0
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==19.3b0]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.8
      hooks:
          - id: flake8
            additional_dependencies: [flake8-bugbear]
